import { supabase } from './supabase';

export const eventsToSeed = [
  {
    name: 'Classical Dance',
    category: 'Dance',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 5,
    min_time_minutes: 8,
    max_time_minutes: 10,
  },
  {
    name: 'UTU Best Dancer',
    category: 'Dance',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 5,
    min_time_minutes: 8,
    max_time_minutes: 10,
  },
  {
    name: 'Folk/Tribal Dance',
    category: 'Dance',
    is_team: true,
    min_team_size: 8,
    max_team_size: 10,
    max_entries_per_institute: 1,
    max_accompanists: 3,
    min_time_minutes: 5,
    max_time_minutes: 8,
  },
  {
    name: 'Free Style/Contemporary/Bollywood Dance',
    category: 'Dance',
    is_team: true,
    min_team_size: 8,
    max_team_size: 10,
    max_entries_per_institute: 1,
    max_accompanists: 5,
    min_time_minutes: 8,
    max_time_minutes: 10,
  },
  {
    name: 'Light Indian Vocal',
    category: 'Music',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 3,
    min_time_minutes: 4,
    max_time_minutes: 6,
  },
  {
    name: 'Western Vocal',
    category: 'Music',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 3,
    min_time_minutes: 4,
    max_time_minutes: 6,
  },
  {
    name: 'Bollywood/Filmy Vocal',
    category: 'Music',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 3,
    min_time_minutes: 4,
    max_time_minutes: 6,
  },
  {
    name: 'Indian Song',
    category: 'Music',
    is_team: true,
    min_team_size: 3,
    max_team_size: 4,
    max_entries_per_institute: 1,
    max_accompanists: 1,
    min_time_minutes: 4,
    max_time_minutes: 6,
  },
  {
    name: 'Mono-Acting',
    category: 'Theatre',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 5,
    max_time_minutes: 8,
  },
  {
    name: 'Mimicry',
    category: 'Theatre',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 5,
    max_time_minutes: 8,
  },
  {
    name: 'Mime',
    category: 'Theatre',
    is_team: true,
    min_team_size: 6,
    max_team_size: 6,
    max_entries_per_institute: 1,
    max_accompanists: 0,
    min_time_minutes: 5,
    max_time_minutes: 8,
  },
  {
    name: 'Skit',
    category: 'Theatre',
    is_team: true,
    min_team_size: 3,
    max_team_size: 6,
    max_entries_per_institute: 1,
    max_accompanists: 4,
    min_time_minutes: 5,
    max_time_minutes: 10,
  },
  {
    name: 'One-Act-Play / Drama',
    category: 'Theatre',
    is_team: true,
    min_team_size: 3,
    max_team_size: 9,
    max_entries_per_institute: 1,
    max_accompanists: 8,
    min_time_minutes: 10,
    max_time_minutes: 30,
  },
  {
    name: 'Short Film Making',
    category: 'Theatre',
    is_team: true,
    min_team_size: 3,
    max_team_size: 6,
    max_entries_per_institute: 1,
    max_accompanists: 0,
    min_time_minutes: 5,
    max_time_minutes: 10,
  },
  {
    name: 'Elocution',
    category: 'Literary',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 4,
    max_time_minutes: 5,
  },
  {
    name: 'Poem Recitation',
    category: 'Literary',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 0,
    max_time_minutes: 5,
  },
  {
    name: 'Quiz',
    category: 'Literary',
    is_team: true,
    min_team_size: 3,
    max_team_size: 3,
    max_entries_per_institute: 1,
    max_accompanists: 0,
    min_time_minutes: null,
    max_time_minutes: null,
  },
  {
    name: 'Debate',
    category: 'Literary',
    is_team: true,
    min_team_size: 2,
    max_team_size: 2,
    max_entries_per_institute: 1,
    max_accompanists: 0,
    min_time_minutes: null,
    max_time_minutes: null,
  },
  {
    name: 'Poster Making',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 4,
    max_time_minutes: 5,
  },
  {
    name: 'On the Spot Painting',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Cartooning',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Collage',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Clay Modelling',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Rangoli',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Mehndi',
    category: 'Fine Arts',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 1,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Fashion Show',
    category: 'Diverse',
    is_team: true,
    min_team_size: 12,
    max_team_size: 16,
    max_entries_per_institute: 1,
    max_accompanists: null,
    min_time_minutes: 120,
    max_time_minutes: 150,
  },
  {
    name: 'Uth Icon [1 Male and 1 Female]',
    category: 'Diverse',
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_entries_per_institute: 2,
    max_accompanists: 8,
    min_time_minutes: 10,
    max_time_minutes: null,
  },
  {
    name: 'Show Reels',
    category: 'Diverse',
    is_team: true,
    min_team_size: 2,
    max_team_size: 3,
    max_entries_per_institute: 2,
    max_accompanists: 0,
    min_time_minutes: 1,
    max_time_minutes: 3,
  },
];

export const seedAllEvents = async () => {
  try {
    const { data, error } = await supabase
      .from('events')
      .insert(eventsToSeed.map((e) => ({ ...e, venue: null, event_date: null, event_time: null, rules_pdf_url: null, is_prelim: null })))
      .select();

    if (error) throw error;
    console.log(`✅ Successfully seeded ${data?.length || 0} events`);
    return data;
  } catch (error) {
    console.error('❌ Error seeding events:', error);
    throw error;
  }
};
